name: Resize & publish to GitHub Pages

on:
  push:
      branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2
            
            - name: Setup ImageMagick
              uses: mfinelli/setup-imagemagick@v5.0.1

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13' 
            
            - name: Resize images
              run: python resize-images.py

            - name: Publish to gh-pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./resized