name: Resize & publish to GitHub Pages

on:
  push:
      branches:
        - main

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2
            
            - name: Install ImageMagick
              run: sudo apt install -y imagemagick

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13' 
            
            - name: Resize images
              run: python resize-images.py

            - name: Setup Git as GitHub Actions bot
              run: | # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Publish to gh-pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./resized