name: resize images & publish on 'alternatives' branch

on:
  push:
      branches:
        - main

permissions:
    contents: write

jobs:
    deploy:
        runs-on: macos-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2

            - name: Install requests pip package
              run: pip install requests
            
            - name: Resize images & create JSON
              run: python resize-and-create-json.py
            
            - name: Create JSON for Mangacollec
              run: python mangacollec.py

            - name: Create README 
              run: python create-readme.py

            - name: Create HTML from README
              run: python create-html-from-readme.py
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish to 'alternatives' branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./resized
                publish_branch: alternatives
                user_name: 'github-actions[bot]' # https://github.com/peaceiris/actions-gh-pages/tree/v3/?tab=readme-ov-file#%EF%B8%8F-set-git-username-and-email
                user_email: '41898282+github-actions[bot]@users.noreply.github.com' # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
                full_commit_message: '${{ github.event.head_commit.message }} ${{ github.event.head_commit.id }}'
